# -*- coding: utf-8 -*-
"""Deberv3Large.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHGeXIQnAzG8xfcyLyiW0j3LFPW8OQyD
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/NLP/Debertv3Large_task2/

!pip install -r requirements.txt

!pip install transformers==4.44.2 peft==0.11.1  datasets==3.0.1 sentencepiece

import transformers, peft, accelerate
print("Transformers:", transformers.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_deberta_binary.py
# 
# 
# import json
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForSequenceClassification,
#     TrainingArguments,
#     Trainer,
#     DataCollatorWithPadding
# )
# from sklearn.model_selection import train_test_split
# import numpy as np
# from sklearn.metrics import f1_score, accuracy_score
# import torch
# 
# 
# def compute_metrics(eval_pred):
#     predictions, labels = eval_pred
#     predictions = np.argmax(predictions, axis=1)
#     return {
#         'accuracy': accuracy_score(labels, predictions),
#         'f1': f1_score(labels, predictions, average='weighted')
#     }
# 
# 
# def load_and_filter_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             item = json.loads(line)
#             if item.get('conspiracy') in ['Yes', 'No']:
#                 data.append(item)
#     return data
# 
# 
# if __name__ == "__main__":
#     model_name = "microsoft/deberta-v3-large"
#     output_dir = "deberta-v3-large-conspiracy-classification"
#     train_file = "train_rehydrated.jsonl"
#     batch_size = 8
#     learning_rate = 1e-5
#     num_epochs = 5
#     max_length = 256
# 
#     print(f"Training model: {model_name}")
# 
#     if torch.cuda.is_available():
#         print(f"Using GPU: {torch.cuda.get_device_name(0)}")
#     else:
#         print("Warning: GPU not available, training on CPU")
# 
#     data = load_and_filter_data(train_file)
#     print(f"Loaded {len(data)} labeled samples")
# 
#     train_data, val_data = train_test_split(
#         data,
#         test_size=0.1,
#         random_state=42,
#         stratify=[d['conspiracy'] for d in data]
#     )
# 
#     print(f"Train: {len(train_data)}, Validation: {len(val_data)}")
# 
#     train_dataset = Dataset.from_list(train_data)
#     val_dataset = Dataset.from_list(val_data)
# 
#     label2id = {"No": 0, "Yes": 1}
#     id2label = {0: "No", 1: "Yes"}
# 
#     def add_labels(example):
#         example['labels'] = label2id[example['conspiracy']]
#         return example
# 
#     train_dataset = train_dataset.map(add_labels)
#     val_dataset = val_dataset.map(add_labels)
# 
#     print(f"Loading tokenizer and model: {model_name}")
#     tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
# 
#     model = AutoModelForSequenceClassification.from_pretrained(
#         model_name,
#         num_labels=2,
#         id2label=id2label,
#         label2id=label2id
#     )
# 
#     def tokenize_function(examples):
#         return tokenizer(
#             examples["text"],
#             truncation=True,
#             max_length=max_length,
#             padding=False
#         )
# 
#     print("Tokenizing datasets...")
#     train_dataset = train_dataset.map(tokenize_function, batched=True)
#     val_dataset = val_dataset.map(tokenize_function, batched=True)
# 
#     data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
# 
#     training_args = TrainingArguments(
#         output_dir=output_dir,
#         eval_strategy="epoch",
#         save_strategy="epoch",
#         learning_rate=learning_rate,
#         per_device_train_batch_size=batch_size,
#         per_device_eval_batch_size=batch_size,
#         num_train_epochs=num_epochs,
#         weight_decay=0.01,
#         save_total_limit=2,
#         load_best_model_at_end=True,
#         metric_for_best_model="f1",
#         fp16=torch.cuda.is_available(),
#         push_to_hub=False,
#         report_to="none",
#         logging_steps=100,
#         dataloader_num_workers=0,
#     )
# 
#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=train_dataset,
#         eval_dataset=val_dataset,
#         tokenizer=tokenizer,
#         data_collator=data_collator,
#         compute_metrics=compute_metrics
#     )
# 
#     print("Starting training...")
#     trainer.train()
# 
#     trainer.save_model(output_dir)
#     tokenizer.save_pretrained(output_dir)
#     print(f"Model saved to {output_dir}")
# 
#     print("Final evaluation on validation set:")
#     results = trainer.evaluate()
#     print(results)

model_name = "microsoft/deberta-v3-large"
batch_size = 8
learning_rate = 1e-5
num_epochs = 5
max_length = 256

!python train_deberta_binary.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer_deberta_binary.py
# 
# import json
# import sys
# import numpy as np
# import os
# import glob
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForSequenceClassification,
#     Trainer,
#     TrainingArguments,
#     DataCollatorWithPadding
# )
# 
# 
# MODEL_PATH = "deberta-v3-large-conspiracy-classification"
# MODEL_NAME = "microsoft/deberta-v3-large"
# TEST_FILE = "dev_rehydrated.jsonl"
# SUBMISSION_FILE = "submission.jsonl"
# LABEL_MAP = {0: "No", 1: "Yes"}
# BATCH_SIZE = 8
# 
# 
# def find_model_directory(base_path):
#     print(f"Checking for model in: {base_path}")
#     return base_path
# 
# 
# def load_test_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for i, line in enumerate(f):
#             try:
#                 item = json.loads(line)
#                 sample_id = item.get("_id", f"sample_{i}")
#                 data.append({
#                     "unique_sample_id": sample_id,
#                     "text": item.get("text", "")
#                 })
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line at index {i}")
#     print(f"Loaded {len(data)} samples for inference")
#     return data
# 
# 
# def tokenize_data(dataset, tokenizer):
#     return dataset.map(lambda examples: tokenizer(examples["text"], truncation=True), batched=True)
# 
# 
# if __name__ == '__main__':
# 
#     raw_data = load_test_data(TEST_FILE)
#     if not raw_data:
#         print("Error: No data loaded")
#         sys.exit(-1)
# 
#     test_dataset = Dataset.from_list(raw_data)
#     unique_ids = test_dataset["unique_sample_id"]
# 
#     model_directory = find_model_directory(MODEL_PATH)
# 
#     print(f"Loading model from {model_directory}...")
#     try:
#         tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
#         model = AutoModelForSequenceClassification.from_pretrained(model_directory)
#     except Exception as e:
#         print(f"Error loading model: {e}")
#         sys.exit(-1)
# 
#     tokenized_test_dataset = tokenize_data(test_dataset, tokenizer)
#     tokenized_test_dataset = tokenized_test_dataset.remove_columns(["unique_sample_id", "text"])
# 
#     data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
# 
#     trainer = Trainer(
#         model=model,
#         args=TrainingArguments(
#             output_dir="./tmp_inference",
#             per_device_eval_batch_size=BATCH_SIZE,
#             report_to="none"
#         ),
#         data_collator=data_collator
#     )
# 
#     print("Starting prediction...")
#     predictions_output = trainer.predict(tokenized_test_dataset)
# 
#     logits = predictions_output.predictions
#     predicted_class_ids = np.argmax(logits, axis=-1)
#     predicted_labels = [LABEL_MAP[int(id)] for id in predicted_class_ids]
# 
#     print(f"Saving {len(predicted_labels)} predictions to {SUBMISSION_FILE}...")
# 
#     with open(SUBMISSION_FILE, 'w') as f:
#         for i, label in enumerate(predicted_labels):
#             submission_obj = {
#                 "_id": unique_ids[i],
#                 "conspiracy": label,
#                 "markers": []
#             }
#             f.write(json.dumps(submission_obj) + '\n')
# 
#     print(f"Submission file generated: {SUBMISSION_FILE}")
# 
#     yes_count = sum(1 for label in predicted_labels if label == "Yes")
#     no_count = sum(1 for label in predicted_labels if label == "No")
#     print(f"Predictions - Yes: {yes_count}, No: {no_count}")

!python infer_deberta_binary.py

import torch
torch.cuda.empty_cache()
import gc
gc.collect()

model_name = "microsoft/deberta-v3-large"
batch_size = 4
learning_rate = 1e-5
num_epochs = 5
max_length = 512

!python train_deberta_binary.py

import torch
torch.cuda.empty_cache()
import gc
gc.collect()

!python infer_deberta_binary.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_deberta_span.py
# 
# 
# import json
# from transformers import (
#     AutoTokenizer,
#     AutoModelForTokenClassification,
#     TrainingArguments,
#     Trainer,
#     DataCollatorForTokenClassification
# )
# from datasets import Dataset
# from sklearn.model_selection import train_test_split
# import torch
# 
# 
# def load_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 data.append(json.loads(line))
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line: {line.strip()}")
#     return data
# 
# 
# def create_label_maps_simplified(marker_type):
#     label_list = ["O", marker_type]
#     label_to_id = {label: i for i, label in enumerate(label_list)}
#     id_to_label = {i: label for label, i in label_to_id.items()}
#     return label_to_id, id_to_label, len(label_list)
# 
# 
# def tokenize_and_align_labels_simplified(examples, tokenizer, label_to_id, marker_type):
#     tokenized_inputs = tokenizer(
#         examples["text"],
#         truncation=True,
#         padding="max_length",
#         max_length=128,
#         return_offsets_mapping=True
#     )
#     labels = []
#     all_markers = examples.get("markers", [])
# 
#     for i, offsets in enumerate(tokenized_inputs["offset_mapping"]):
#         example_labels = [0] * len(offsets)
#         example_markers = all_markers[i] if i < len(all_markers) else []
# 
#         for marker in example_markers:
#             if marker["type"] == marker_type:
#                 start_char = marker["startIndex"]
#                 end_char = marker["endIndex"]
#                 marker_label = label_to_id.get(marker_type)
#                 if marker_label is not None:
#                     for token_idx, (start, end) in enumerate(offsets):
#                         if start is not None and end is not None:
#                             if start_char <= start < end_char:
#                                 if token_idx < len(example_labels):
#                                     example_labels[token_idx] = marker_label
#                             elif start < end_char and end > start_char:
#                                 if token_idx < len(example_labels) and example_labels[token_idx] == 0:
#                                     example_labels[token_idx] = marker_label
#         labels.append(example_labels)
# 
#     tokenized_inputs["labels"] = labels
#     return tokenized_inputs
# 
# 
# if __name__ == "__main__":
#     train_file = "train_rehydrated.jsonl"
#     model_name = "microsoft/deberta-v3-large"
#     output_dir_base = "deberta-v3-large-span"
#     batch_size = 8
#     learning_rate = 1e-5
#     num_epochs = 5
#     marker_types_to_train = ["Action", "Actor", "Effect", "Evidence", "Victim"]
# 
#     print(f"Loading data from {train_file}...")
#     train_data = load_data(train_file)
#     print(f"Loaded {len(train_data)} samples")
# 
#     print(f"Loading tokenizer: {model_name}")
#     tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
# 
#     for marker_type in marker_types_to_train:
#         print(f"\n{'='*60}")
#         print(f"Training model for marker type: {marker_type}")
#         print(f"{'='*60}")
# 
#         label_to_id, id_to_label, num_labels = create_label_maps_simplified(marker_type)
#         print(f"Labels: {label_to_id}")
# 
#         train_dataset = Dataset.from_list(train_data)
# 
#         tokenized_train_dataset = train_dataset.map(
#             tokenize_and_align_labels_simplified,
#             batched=True,
#             fn_kwargs={"tokenizer": tokenizer, "label_to_id": label_to_id, "marker_type": marker_type}
#         )
# 
#         print(f"Loading model: {model_name}")
#         model = AutoModelForTokenClassification.from_pretrained(
#             model_name,
#             num_labels=num_labels,
#             id2label=id_to_label,
#             label2id=label_to_id
#         )
# 
#         output_dir = f"{output_dir_base}-{marker_type}"
# 
#         training_args = TrainingArguments(
#             output_dir=output_dir,
#             learning_rate=learning_rate,
#             per_device_train_batch_size=batch_size,
#             per_device_eval_batch_size=batch_size,
#             num_train_epochs=num_epochs,
#             weight_decay=0.01,
#             save_strategy="epoch",
#             save_total_limit=2,
#             logging_dir=f'./logs-{marker_type}',
#             logging_steps=100,
#             report_to="none",
#             fp16=torch.cuda.is_available(),
#         )
# 
#         data_collator = DataCollatorForTokenClassification(tokenizer)
# 
#         trainer = Trainer(
#             model=model,
#             args=training_args,
#             train_dataset=tokenized_train_dataset,
#             data_collator=data_collator,
#             tokenizer=tokenizer,
#         )
# 
#         print(f"Starting training for {marker_type}...")
#         trainer.train()
# 
#         trainer.save_model(output_dir)
#         tokenizer.save_pretrained(output_dir)
# 
#         print(f"Training for {marker_type} completed")
#         print(f"Model saved to {output_dir}")
# 
#     print(f"\n{'='*60}")
#     print("All 5 models trained successfully!")
#     print(f"{'='*60}")
#     print("\nOutput directories:")
#     for marker_type in marker_types_to_train:
#         print(f"  - {output_dir_base}-{marker_type}/")

!python train_deberta_span.py

"""## Only for victim

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_victim.py
# 
# import json
# from transformers import (
#     AutoTokenizer,
#     AutoModelForTokenClassification,
#     TrainingArguments,
#     Trainer,
#     DataCollatorForTokenClassification
# )
# from datasets import Dataset
# import torch
# 
# 
# def load_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 data.append(json.loads(line))
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line: {line.strip()}")
#     return data
# 
# 
# def create_label_maps_simplified(marker_type):
#     label_list = ["O", marker_type]
#     label_to_id = {label: i for i, label in enumerate(label_list)}
#     id_to_label = {i: label for label, i in label_to_id.items()}
#     return label_to_id, id_to_label, len(label_list)
# 
# 
# def tokenize_and_align_labels_simplified(examples, tokenizer, label_to_id, marker_type):
#     tokenized_inputs = tokenizer(
#         examples["text"],
#         truncation=True,
#         padding="max_length",
#         max_length=128,
#         return_offsets_mapping=True
#     )
#     labels = []
#     all_markers = examples.get("markers", [])
# 
#     for i, offsets in enumerate(tokenized_inputs["offset_mapping"]):
#         example_labels = [0] * len(offsets)
#         example_markers = all_markers[i] if i < len(all_markers) else []
# 
#         for marker in example_markers:
#             if marker["type"] == marker_type:
#                 start_char = marker["startIndex"]
#                 end_char = marker["endIndex"]
#                 marker_label = label_to_id.get(marker_type)
#                 if marker_label is not None:
#                     for token_idx, (start, end) in enumerate(offsets):
#                         if start is not None and end is not None:
#                             if start_char <= start < end_char:
#                                 if token_idx < len(example_labels):
#                                     example_labels[token_idx] = marker_label
#                             elif start < end_char and end > start_char:
#                                 if token_idx < len(example_labels) and example_labels[token_idx] == 0:
#                                     example_labels[token_idx] = marker_label
#         labels.append(example_labels)
# 
#     tokenized_inputs["labels"] = labels
#     return tokenized_inputs
# 
# 
# if __name__ == "__main__":
#     train_file = "train_rehydrated.jsonl"
#     model_name = "microsoft/deberta-v3-large"
#     marker_type = "Victim"
#     output_dir = f"deberta-v3-large-span-{marker_type}"
# 
#     use_cpu = not torch.cuda.is_available()
# 
#     if use_cpu:
#         print("="*60)
#         print("WARNING: Training on CPU")
#         print("This will take 10-15 hours instead of 35 minutes on GPU")
#         print("Consider waiting for GPU quota or using Kaggle")
#         print("="*60)
# 
#         batch_size = 4
#         learning_rate = 1e-5
#         num_epochs = 3
#         fp16 = False
#     else:
#         print("Using GPU")
#         batch_size = 8
#         learning_rate = 1e-5
#         num_epochs = 5
#         fp16 = True
# 
#     print(f"\nLoading data from {train_file}...")
#     train_data = load_data(train_file)
#     print(f"Loaded {len(train_data)} samples")
# 
#     print(f"\nLoading tokenizer: {model_name}")
#     tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
# 
#     print(f"\n{'='*60}")
#     print(f"Training model for marker type: {marker_type}")
#     print(f"{'='*60}")
# 
#     label_to_id, id_to_label, num_labels = create_label_maps_simplified(marker_type)
#     print(f"Labels: {label_to_id}")
# 
#     train_dataset = Dataset.from_list(train_data)
# 
#     print("Tokenizing dataset...")
#     tokenized_train_dataset = train_dataset.map(
#         tokenize_and_align_labels_simplified,
#         batched=True,
#         fn_kwargs={"tokenizer": tokenizer, "label_to_id": label_to_id, "marker_type": marker_type}
#     )
# 
#     print(f"Loading model: {model_name}")
#     model = AutoModelForTokenClassification.from_pretrained(
#         model_name,
#         num_labels=num_labels,
#         id2label=id_to_label,
#         label2id=label_to_id
#     )
# 
#     training_args = TrainingArguments(
#         output_dir=output_dir,
#         learning_rate=learning_rate,
#         per_device_train_batch_size=batch_size,
#         per_device_eval_batch_size=batch_size,
#         num_train_epochs=num_epochs,
#         weight_decay=0.01,
#         save_strategy="epoch",
#         save_total_limit=2,
#         logging_dir=f'./logs-{marker_type}',
#         logging_steps=100,
#         report_to="none",
#         fp16=fp16,
#         dataloader_num_workers=0,
#     )
# 
#     data_collator = DataCollatorForTokenClassification(tokenizer)
# 
#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=tokenized_train_dataset,
#         data_collator=data_collator,
#         tokenizer=tokenizer,
#     )
# 
#     print(f"\nStarting training for {marker_type}...")
#     if use_cpu:
#         print("Training on CPU - this will take several hours")
#         print("You can stop anytime with Ctrl+C")
# 
#     trainer.train()
# 
#     trainer.save_model(output_dir)
#     tokenizer.save_pretrained(output_dir)
# 
#     print(f"\n{'='*60}")
#     print(f"Training for {marker_type} completed")
#     print(f"Model saved to {output_dir}")
#     print(f"{'='*60}")
# 
#     if use_cpu:
#         print("\nNote: CPU training completed.")
#         print("GPU training would have been much faster.")

!python train_victim.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer_deberta_span.py
# 
# import json
# import sys
# import numpy as np
# import os
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForTokenClassification,
#     Trainer,
#     TrainingArguments,
#     DataCollatorForTokenClassification
# )
# from collections import defaultdict
# 
# 
# MODEL_PATH_BASE = "deberta-v3-large-span"
# MODEL_NAME = "microsoft/deberta-v3-large"
# MARKER_TYPES_TO_INFER = ["Action", "Actor", "Effect", "Evidence", "Victim"]
# TEST_FILE = "dev_rehydrated.jsonl"
# SUBMISSION_FILE = "submission.jsonl"
# BATCH_SIZE = 8
# 
# 
# def load_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for i, line in enumerate(f):
#             try:
#                 item = json.loads(line.strip())
#                 item["_id"] = item.get("_id", f"sample_{i}")
#                 item["text"] = item.get("text", "")
#                 item["markers"] = item.get("markers", [])
#                 item["conspiracy"] = item.get("conspiracy", "No")
#                 data.append(item)
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line at index {i}")
#     print(f"Loaded {len(data)} samples for inference")
#     return data
# 
# 
# def tokenize_and_align_labels(examples, tokenizer, label_to_id):
#     tokenized_inputs = tokenizer(
#         examples["text"],
#         truncation=True,
#         padding="max_length",
#         max_length=128,
#         return_offsets_mapping=True
#     )
#     tokenized_inputs["labels"] = [[-100] * len(offset_map) for offset_map in tokenized_inputs["offset_mapping"]]
#     return tokenized_inputs
# 
# 
# def reconstruct_spans(predictions, tokenized_dataset, id_to_label):
#     reconstructed_markers = defaultdict(list)
# 
#     positive_label_type = id_to_label.get(1)
#     if not positive_label_type or positive_label_type == "O":
#         print("Error: Model configuration mismatch")
#         return reconstructed_markers
# 
#     for i, pred_ids in enumerate(predictions):
#         offsets = tokenized_dataset[i]['offset_mapping']
#         original_text = tokenized_dataset[i]['text']
#         current_span_start_char = None
# 
#         for token_idx, label_id in enumerate(pred_ids):
#             offset_tuple = offsets[token_idx]
# 
#             is_special = (offset_tuple is None or offset_tuple[0] is None or
#                          offset_tuple[1] is None or (offset_tuple[0] == 0 and offset_tuple[1] == 0))
# 
#             if is_special:
#                 if current_span_start_char is not None:
#                     prev_end_char = None
#                     if token_idx > 0 and offsets[token_idx - 1][1] is not None:
#                         prev_end_char = offsets[token_idx - 1][1]
# 
#                     if prev_end_char is not None:
#                         span_text = original_text[current_span_start_char:prev_end_char]
#                         reconstructed_markers[i].append({
#                             "startIndex": current_span_start_char,
#                             "endIndex": prev_end_char,
#                             "type": positive_label_type,
#                             "text": span_text
#                         })
#                     current_span_start_char = None
#                 continue
# 
#             label = id_to_label[label_id]
#             start_char = offset_tuple[0]
# 
#             if label == positive_label_type:
#                 if current_span_start_char is None:
#                     current_span_start_char = start_char
# 
#             elif label == 'O':
#                 if current_span_start_char is not None:
#                     prev_end_char = offsets[token_idx - 1][1] if token_idx > 0 and offsets[token_idx - 1][1] is not None else start_char
#                     span_text = original_text[current_span_start_char:prev_end_char]
#                     reconstructed_markers[i].append({
#                         "startIndex": current_span_start_char,
#                         "endIndex": prev_end_char,
#                         "type": positive_label_type,
#                         "text": span_text
#                     })
#                     current_span_start_char = None
# 
#         if current_span_start_char is not None:
#             last_valid_end = None
#             last_token_idx = len(pred_ids) - 1
#             while last_token_idx >= 0:
#                 offset_tuple_end = offsets[last_token_idx]
#                 if offset_tuple_end is not None and offset_tuple_end[1] is not None and offset_tuple_end[1] != 0:
#                     last_valid_end = offset_tuple_end[1]
#                     break
#                 last_token_idx -= 1
# 
#             if last_valid_end is not None:
#                 span_text = original_text[current_span_start_char:last_valid_end]
#                 reconstructed_markers[i].append({
#                     "startIndex": current_span_start_char,
#                     "endIndex": last_valid_end,
#                     "type": positive_label_type,
#                     "text": span_text
#                 })
# 
#     return reconstructed_markers
# 
# 
# if __name__ == '__main__':
# 
#     raw_data = load_data(TEST_FILE)
#     if not raw_data:
#         print("Error: No data loaded")
#         sys.exit(-1)
# 
#     unique_ids = [d["_id"] for d in raw_data]
#     conspiracy_keys = [d["conspiracy"] for d in raw_data]
# 
#     test_dataset = Dataset.from_list(raw_data)
# 
#     print(f"Loading tokenizer: {MODEL_NAME}")
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
# 
#     dummy_label_to_id = {"O": 0}
# 
#     tokenized_test_dataset = test_dataset.map(
#         tokenize_and_align_labels,
#         batched=True,
#         remove_columns=[col for col in test_dataset.column_names if
#                        col not in ['text', 'offset_mapping', '_id', 'conspiracy']],
#         fn_kwargs={"tokenizer": tokenizer, "label_to_id": dummy_label_to_id}
#     )
# 
#     all_predicted_markers = defaultdict(list)
# 
#     for marker_type in MARKER_TYPES_TO_INFER:
# 
#         model_directory = f"{MODEL_PATH_BASE}-{marker_type}"
# 
#         print(f"\n{'='*60}")
#         print(f"Running inference for: {marker_type}")
#         print(f"{'='*60}")
#         print(f"Loading model from: {model_directory}")
# 
#         try:
#             model = AutoModelForTokenClassification.from_pretrained(model_directory)
#             id_to_label = {0: "O", 1: marker_type}
#             print(f"Labels: {id_to_label}")
# 
#         except Exception as e:
#             print(f"Error loading model for {marker_type}: {e}")
#             continue
# 
#         data_collator = DataCollatorForTokenClassification(tokenizer)
# 
#         trainer = Trainer(
#             model=model,
#             args=TrainingArguments(
#                 output_dir=f"./tmp_inference_span_{marker_type}",
#                 per_device_eval_batch_size=BATCH_SIZE,
#                 report_to="none"
#             ),
#             data_collator=data_collator,
#             tokenizer=tokenizer
#         )
# 
#         print(f"Running predictions...")
#         predictions_output = trainer.predict(tokenized_test_dataset)
# 
#         logits = predictions_output.predictions
#         predicted_class_ids = np.argmax(logits, axis=2)
# 
#         print(f"Reconstructing character spans...")
#         current_marker_map = reconstruct_spans(predicted_class_ids, tokenized_test_dataset, id_to_label)
# 
#         for i, markers in current_marker_map.items():
#             all_predicted_markers[i].extend(markers)
# 
#         print(f"Found {sum(len(m) for m in current_marker_map.values())} spans for {marker_type}")
# 
#     print(f"\n{'='*60}")
#     print(f"Saving predictions to {SUBMISSION_FILE}")
#     print(f"{'='*60}")
# 
#     with open(SUBMISSION_FILE, 'w') as f:
#         for i in range(len(raw_data)):
#             predicted_markers = all_predicted_markers.get(i, [])
# 
#             jsonl_obj = {
#                 "_id": unique_ids[i],
#                 "conspiracy": conspiracy_keys[i],
#                 "markers": predicted_markers
#             }
#             f.write(json.dumps(jsonl_obj) + '\n')
# 
#     total_markers = sum(len(all_predicted_markers.get(i, [])) for i in range(len(raw_data)))
#     print(f"\nSubmission file generated: {SUBMISSION_FILE}")
#     print(f"Total samples: {len(raw_data)}")
#     print(f"Total markers predicted: {total_markers}")
# 
#     for marker_type in MARKER_TYPES_TO_INFER:
#         count = sum(1 for i in range(len(raw_data))
#                    for m in all_predicted_markers.get(i, [])
#                    if m['type'] == marker_type)
#         print(f"  {marker_type}: {count}")

!python infer_deberta_span.py

