# -*- coding: utf-8 -*-
"""LLama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qd5AfUucmka_sr3CX7duTuOmVhO7buOL
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/NLP/LLama/

!pip install -q peft==0.13.2 bitsandbytes==0.45.0

!pip install -U transformers



#!pip install triton

#!pip install --upgrade triton

#!pip uninstall -y bitsandbytes
!pip install git+https://github.com/TimDettmers/bitsandbytes.git

import os
os.kill(os.getpid(), 9)

import bitsandbytes as bnb
print("bitsandbytes working")

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B")
print("Access verified")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_llama_lora.py
# 
# import torch
# import json
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForCausalLM,
#     TrainingArguments,
#     Trainer,
#     DataCollatorForLanguageModeling
# )
# from peft import LoraConfig, get_peft_model
# import numpy as np
# from sklearn.metrics import accuracy_score, f1_score
# 
# MODEL_NAME = "meta-llama/Meta-Llama-3.1-8B"
# OUTPUT_DIR = "llama-3.1-8b-conspiracy-lora-v2"
# TRAIN_FILE = "train_rehydrated.jsonl"
# MAX_LENGTH = 512
# BATCH_SIZE = 2
# GRADIENT_ACCUMULATION = 8
# LEARNING_RATE = 1e-4
# NUM_EPOCHS = 5
# WARMUP_STEPS = 200
# SAVE_STEPS = 200
# LOGGING_STEPS = 50
# VAL_SPLIT = 0.1
# 
# LORA_CONFIG = LoraConfig(
#     r=16,
#     lora_alpha=32,
#     target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
#     lora_dropout=0.05,
#     bias="none",
#     task_type="CAUSAL_LM"
# )
# 
# 
# def load_and_format_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 item = json.loads(line)
#                 if item.get('conspiracy') in ['Yes', 'No']:
#                     prompt = f"""### Task: Classify if this is conspiracy theory content. Answer only 'Yes' or 'No'.
# 
# ### Text: {item['text']}
# 
# ### Answer: {item['conspiracy']}"""
# 
#                     data.append({
#                         'text': prompt,
#                         'label': item['conspiracy']
#                     })
#             except json.JSONDecodeError:
#                 continue
# 
#     return data
# 
# 
# def tokenize_function(examples, tokenizer):
#     outputs = tokenizer(
#         examples['text'],
#         truncation=True,
#         max_length=MAX_LENGTH,
#         padding='max_length',
#         return_tensors=None
#     )
#     outputs["labels"] = outputs["input_ids"].copy()
#     return outputs
# 
# 
# def compute_metrics(eval_pred):
#     predictions, labels = eval_pred
#     predictions = predictions[0] if isinstance(predictions, tuple) else predictions
# 
#     decoded_preds = []
#     decoded_labels = []
# 
#     for pred_seq, label_seq in zip(predictions, labels):
#         pred_tokens = pred_seq[label_seq != -100]
#         pred_text = tokenizer.decode(pred_tokens, skip_special_tokens=True).strip()
# 
#         if 'yes' in pred_text.lower()[:20]:
#             decoded_preds.append(1)
#         else:
#             decoded_preds.append(0)
# 
#         label_text = tokenizer.decode([t for t in label_seq if t != -100], skip_special_tokens=True).strip()
#         decoded_labels.append(1 if 'yes' in label_text.lower() else 0)
# 
#     decoded_preds = np.array(decoded_preds)
#     decoded_labels = np.array(decoded_labels)
# 
#     return {
#         'accuracy': accuracy_score(decoded_labels, decoded_preds),
#         'f1_weighted': f1_score(decoded_labels, decoded_preds, average='weighted', zero_division=0)
#     }
# 
# 
# def main():
#     print(f"Loading data from {TRAIN_FILE}...")
#     data = load_and_format_data(TRAIN_FILE)
#     print(f"Loaded {len(data)} samples")
# 
#     split_idx = int(len(data) * (1 - VAL_SPLIT))
#     train_data = data[:split_idx]
#     val_data = data[split_idx:]
# 
#     print(f"Training samples: {len(train_data)}")
#     print(f"Validation samples: {len(val_data)}")
# 
#     train_dataset = Dataset.from_list(train_data)
#     val_dataset = Dataset.from_list(val_data)
# 
#     print(f"Loading tokenizer and model: {MODEL_NAME}")
#     global tokenizer
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
#     tokenizer.pad_token = tokenizer.eos_token
#     tokenizer.padding_side = "right"
# 
#     model = AutoModelForCausalLM.from_pretrained(
#         MODEL_NAME,
#         device_map="auto",
#         torch_dtype=torch.float16,
#         trust_remote_code=True,
#         low_cpu_mem_usage=True
#     )
# 
#     for param in model.parameters():
#         param.requires_grad = False
#         if param.ndim == 1:
#             param.data = param.data.to(torch.float32)
# 
#     model.gradient_checkpointing_enable()
#     model.enable_input_require_grads()
# 
#     model = get_peft_model(model, LORA_CONFIG)
# 
#     print(f"Trainable parameters: {model.print_trainable_parameters()}")
# 
#     tokenized_train = train_dataset.map(
#         lambda x: tokenize_function(x, tokenizer),
#         batched=True,
#         remove_columns=train_dataset.column_names
#     )
# 
#     tokenized_val = val_dataset.map(
#         lambda x: tokenize_function(x, tokenizer),
#         batched=True,
#         remove_columns=val_dataset.column_names
#     )
# 
#     data_collator = DataCollatorForLanguageModeling(
#         tokenizer=tokenizer,
#         mlm=False
#     )
# 
#     training_args = TrainingArguments(
#         output_dir=OUTPUT_DIR,
#         num_train_epochs=NUM_EPOCHS,
#         per_device_train_batch_size=BATCH_SIZE,
#         per_device_eval_batch_size=BATCH_SIZE,
#         gradient_accumulation_steps=GRADIENT_ACCUMULATION,
#         learning_rate=LEARNING_RATE,
#         warmup_steps=WARMUP_STEPS,
#         logging_steps=LOGGING_STEPS,
#         save_steps=SAVE_STEPS,
#         eval_strategy="no",
#         save_strategy="steps",
#         load_best_model_at_end=False,
#         fp16=True,
#         lr_scheduler_type="cosine",
#         report_to="none",
#         save_total_limit=3,
#     )
# 
#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=tokenized_train,
#         eval_dataset=tokenized_val,
#         data_collator=data_collator,
#         compute_metrics=compute_metrics,
#     )
# 
#     print("Starting training...")
#     print(f"Config: LR={LEARNING_RATE}, Epochs={NUM_EPOCHS}, Warmup={WARMUP_STEPS}")
#     trainer.train()
# 
#     print(f"Saving final model to {OUTPUT_DIR}")
#     trainer.save_model(OUTPUT_DIR)
#     tokenizer.save_pretrained(OUTPUT_DIR)
# 
#     print("Training completed")
# 
# 
# if __name__ == "__main__":
#     main()

with open('train_llama_lora.py', 'r') as f:
    content = f.read()

content = content.replace('eval_strategy="steps",', 'eval_strategy="no",')
content = content.replace('load_best_model_at_end=True,', 'load_best_model_at_end=False,')
content = content.replace('SAVE_STEPS = 500', 'SAVE_STEPS = 200')

with open('train_llama_lora.py', 'w') as f:
    f.write(content)

print("Fixed: No evaluation, save every 200 steps")

import torch
torch.cuda.empty_cache()
import gc
gc.collect()
print("Memory cleared")

!python train_llama_lora.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer_llama_lora.py
# 
# import torch
# import json
# from transformers import AutoTokenizer, AutoModelForCausalLM
# from peft import PeftModel
# from tqdm import tqdm
# 
# MODEL_BASE = "meta-llama/Meta-Llama-3.1-8B"
# LORA_WEIGHTS = "llama-3.1-8b-conspiracy-lora-v2"
# TEST_FILE = "dev_rehydrated.jsonl"
# SUBMISSION_FILE = "submission.jsonl"
# BATCH_SIZE = 8
# MAX_NEW_TOKENS = 10
# 
# 
# def load_model_and_tokenizer():
#     print(f"Loading tokenizer from {MODEL_BASE}")
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_BASE)
#     tokenizer.pad_token = tokenizer.eos_token
#     tokenizer.padding_side = "right"
# 
#     print(f"Loading base model: {MODEL_BASE}")
#     model = AutoModelForCausalLM.from_pretrained(
#         MODEL_BASE,
#         device_map="auto",
#         torch_dtype=torch.float16,
#         trust_remote_code=True,
#         low_cpu_mem_usage=True
#     )
# 
#     print(f"Loading LoRA weights from {LORA_WEIGHTS}")
#     model = PeftModel.from_pretrained(model, LORA_WEIGHTS)
#     model = model.merge_and_unload()
#     model.eval()
# 
#     return model, tokenizer
# 
# 
# def format_prompt(text):
#     prompt = f"""### Task: Classify if this is conspiracy theory content. Answer only 'Yes' or 'No'.
# 
# ### Text: {text}
# 
# ### Answer:"""
#     return prompt
# 
# 
# def extract_answer(generated_text):
#     text = generated_text.lower().strip()
# 
#     if text.startswith('yes'):
#         return 'Yes'
#     elif text.startswith('no'):
#         return 'No'
# 
#     if 'yes' in text[:50]:
#         return 'Yes'
#     elif 'no' in text[:50]:
#         return 'No'
# 
#     return 'No'
# 
# 
# def load_test_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 item = json.loads(line)
#                 data.append({
#                     '_id': item.get('_id', ''),
#                     'text': item.get('text', '')
#                 })
#             except json.JSONDecodeError:
#                 continue
#     return data
# 
# 
# def predict_batch(model, tokenizer, texts):
#     prompts = [format_prompt(text) for text in texts]
# 
#     inputs = tokenizer(
#         prompts,
#         return_tensors="pt",
#         padding=True,
#         truncation=True,
#         max_length=512
#     ).to(model.device)
# 
#     with torch.no_grad():
#         outputs = model.generate(
#             **inputs,
#             max_new_tokens=MAX_NEW_TOKENS,
#             temperature=0.1,
#             do_sample=False,
#             pad_token_id=tokenizer.eos_token_id
#         )
# 
#     predictions = []
#     for i, output in enumerate(outputs):
#         input_length = inputs['input_ids'][i].shape[0]
#         generated_tokens = output[input_length:]
#         generated_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
#         answer = extract_answer(generated_text)
#         predictions.append(answer)
# 
#     return predictions
# 
# 
# def main():
#     print("Loading model and tokenizer...")
#     model, tokenizer = load_model_and_tokenizer()
# 
#     print(f"Loading test data from {TEST_FILE}")
#     test_data = load_test_data(TEST_FILE)
#     print(f"Loaded {len(test_data)} samples")
# 
#     results = []
# 
#     print("Running inference...")
#     for i in tqdm(range(0, len(test_data), BATCH_SIZE)):
#         batch = test_data[i:i + BATCH_SIZE]
#         texts = [item['text'] for item in batch]
#         ids = [item['_id'] for item in batch]
# 
#         predictions = predict_batch(model, tokenizer, texts)
# 
#         for doc_id, pred in zip(ids, predictions):
#             results.append({
#                 '_id': doc_id,
#                 'conspiracy': pred
#             })
# 
#     print(f"Saving predictions to {SUBMISSION_FILE}")
#     with open(SUBMISSION_FILE, 'w') as f:
#         for result in results:
#             f.write(json.dumps(result) + '\n')
# 
#     print(f"Inference completed. Generated {len(results)} predictions")
# 
# 
# if __name__ == "__main__":
#     main()

!python infer_llama_lora.py

"""# TASK 2"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_llama_span.py
# 
# 
# import torch
# import json
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForCausalLM,
#     TrainingArguments,
#     Trainer,
#     DataCollatorForLanguageModeling
# )
# from peft import LoraConfig, get_peft_model
# 
# MODEL_NAME = "meta-llama/Meta-Llama-3.1-8B"
# OUTPUT_DIR = "llama-3.1-8b-span-extraction-lora"
# TRAIN_FILE = "train_rehydrated.jsonl"
# MAX_LENGTH = 1024
# BATCH_SIZE = 1
# GRADIENT_ACCUMULATION = 16
# LEARNING_RATE = 1e-4
# NUM_EPOCHS = 3
# WARMUP_STEPS = 200
# SAVE_STEPS = 300
# LOGGING_STEPS = 50
# VAL_SPLIT = 0.1
# 
# LORA_CONFIG = LoraConfig(
#     r=16,
#     lora_alpha=32,
#     target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
#     lora_dropout=0.05,
#     bias="none",
#     task_type="CAUSAL_LM"
# )
# 
# 
# def format_markers_as_json(markers):
#     if not markers:
#         return "[]"
# 
#     marker_list = []
#     for m in markers:
#         marker_list.append({
#             "text": m.get("text", ""),
#             "type": m.get("type", ""),
#             "startIndex": m.get("startIndex", 0),
#             "endIndex": m.get("endIndex", 0)
#         })
# 
#     return json.dumps(marker_list, ensure_ascii=False)
# 
# 
# def load_and_format_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 item = json.loads(line)
#                 if item.get('conspiracy') == 'Yes' and item.get('markers'):
#                     markers_json = format_markers_as_json(item['markers'])
# 
#                     prompt = f"""### Task: Extract conspiracy theory markers from the text. Identify spans for: Action, Actor, Effect, Evidence, Victim.
# 
# ### Text: {item['text']}
# 
# ### Markers: {markers_json}"""
# 
#                     data.append({'text': prompt})
#             except json.JSONDecodeError:
#                 continue
# 
#     return data
# 
# 
# def tokenize_function(examples, tokenizer):
#     outputs = tokenizer(
#         examples['text'],
#         truncation=True,
#         max_length=MAX_LENGTH,
#         padding='max_length',
#         return_tensors=None
#     )
#     outputs["labels"] = outputs["input_ids"].copy()
#     return outputs
# 
# 
# def main():
#     print(f"Loading data from {TRAIN_FILE}...")
#     data = load_and_format_data(TRAIN_FILE)
#     print(f"Loaded {len(data)} samples with markers")
# 
#     split_idx = int(len(data) * (1 - VAL_SPLIT))
#     train_data = data[:split_idx]
#     val_data = data[split_idx:]
# 
#     print(f"Training samples: {len(train_data)}")
#     print(f"Validation samples: {len(val_data)}")
# 
#     train_dataset = Dataset.from_list(train_data)
#     val_dataset = Dataset.from_list(val_data)
# 
#     print(f"Loading tokenizer and model: {MODEL_NAME}")
#     global tokenizer
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
#     tokenizer.pad_token = tokenizer.eos_token
#     tokenizer.padding_side = "right"
# 
#     model = AutoModelForCausalLM.from_pretrained(
#         MODEL_NAME,
#         device_map="auto",
#         torch_dtype=torch.float16,
#         trust_remote_code=True,
#         low_cpu_mem_usage=True
#     )
# 
#     for param in model.parameters():
#         param.requires_grad = False
#         if param.ndim == 1:
#             param.data = param.data.to(torch.float32)
# 
#     model.gradient_checkpointing_enable()
#     model.enable_input_require_grads()
# 
#     model = get_peft_model(model, LORA_CONFIG)
# 
#     print(f"Trainable parameters: {model.print_trainable_parameters()}")
# 
#     tokenized_train = train_dataset.map(
#         lambda x: tokenize_function(x, tokenizer),
#         batched=True,
#         remove_columns=train_dataset.column_names
#     )
# 
#     tokenized_val = val_dataset.map(
#         lambda x: tokenize_function(x, tokenizer),
#         batched=True,
#         remove_columns=val_dataset.column_names
#     )
# 
#     data_collator = DataCollatorForLanguageModeling(
#         tokenizer=tokenizer,
#         mlm=False
#     )
# 
#     training_args = TrainingArguments(
#         output_dir=OUTPUT_DIR,
#         num_train_epochs=NUM_EPOCHS,
#         per_device_train_batch_size=BATCH_SIZE,
#         per_device_eval_batch_size=BATCH_SIZE,
#         gradient_accumulation_steps=GRADIENT_ACCUMULATION,
#         learning_rate=LEARNING_RATE,
#         warmup_steps=WARMUP_STEPS,
#         logging_steps=LOGGING_STEPS,
#         save_steps=SAVE_STEPS,
#         eval_strategy="no",
#         save_strategy="steps",
#         load_best_model_at_end=False,
#         fp16=True,
#         lr_scheduler_type="cosine",
#         report_to="none",
#         save_total_limit=3,
#     )
# 
#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=tokenized_train,
#         eval_dataset=tokenized_val,
#         data_collator=data_collator,
#     )
# 
#     print("Starting training...")
#     print(f"Config: LR={LEARNING_RATE}, Epochs={NUM_EPOCHS}, Max_length={MAX_LENGTH}")
#     trainer.train()
# 
#     print(f"Saving final model to {OUTPUT_DIR}")
#     trainer.save_model(OUTPUT_DIR)
#     tokenizer.save_pretrained(OUTPUT_DIR)
# 
#     print("Training completed")
# 
# 
# if __name__ == "__main__":
#     main()

!python train_llama_span.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer_llama_span.py
# 
# import torch
# import json
# import re
# from transformers import AutoTokenizer, AutoModelForCausalLM
# from peft import PeftModel
# from tqdm import tqdm
# 
# MODEL_BASE = "meta-llama/Meta-Llama-3.1-8B"
# LORA_WEIGHTS = "llama-3.1-8b-span-extraction-lora"
# TEST_FILE = "dev_rehydrated.jsonl"
# SUBMISSION_FILE = "submission.jsonl"
# BATCH_SIZE = 4
# MAX_NEW_TOKENS = 512
# 
# 
# def load_model_and_tokenizer():
#     print(f"Loading tokenizer from {MODEL_BASE}")
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_BASE)
#     tokenizer.pad_token = tokenizer.eos_token
#     tokenizer.padding_side = "right"
# 
#     print(f"Loading base model: {MODEL_BASE}")
#     model = AutoModelForCausalLM.from_pretrained(
#         MODEL_BASE,
#         device_map="auto",
#         torch_dtype=torch.float16,
#         trust_remote_code=True,
#         low_cpu_mem_usage=True
#     )
# 
#     print(f"Loading LoRA weights from {LORA_WEIGHTS}")
#     model = PeftModel.from_pretrained(model, LORA_WEIGHTS)
#     model = model.merge_and_unload()
#     model.eval()
# 
#     return model, tokenizer
# 
# 
# def format_prompt(text):
#     prompt = f"""### Task: Extract conspiracy theory markers from the text. Identify spans for: Action, Actor, Effect, Evidence, Victim.
# 
# ### Text: {text}
# 
# ### Markers:"""
#     return prompt
# 
# 
# def extract_markers_from_generation(generated_text, original_text):
#     try:
#         json_match = re.search(r'\[.*?\]', generated_text, re.DOTALL)
#         if not json_match:
#             return []
# 
#         json_str = json_match.group(0)
# 
#         json_str_clean = json_str.replace('\n', ' ').replace('\r', '')
# 
#         try:
#             markers = json.loads(json_str_clean)
#         except json.JSONDecodeError:
#             json_str_fixed = re.sub(r',\s*}', '}', json_str_clean)
#             json_str_fixed = re.sub(r',\s*\]', ']', json_str_fixed)
#             markers = json.loads(json_str_fixed)
# 
#         if not isinstance(markers, list):
#             return []
# 
#         validated_markers = []
#         for m in markers:
#             if not isinstance(m, dict):
#                 continue
# 
#             if not all(k in m for k in ['text', 'type', 'startIndex', 'endIndex']):
#                 continue
# 
#             if m['type'] not in ['Action', 'Actor', 'Effect', 'Evidence', 'Victim']:
#                 continue
# 
#             start = m['startIndex']
#             end = m['endIndex']
# 
#             if not (isinstance(start, int) and isinstance(end, int)):
#                 continue
# 
#             if not (0 <= start < end <= len(original_text)):
#                 continue
# 
#             validated_markers.append({
#                 'text': m['text'],
#                 'type': m['type'],
#                 'startIndex': start,
#                 'endIndex': end
#             })
# 
#         return validated_markers
# 
#     except Exception as e:
#         print(f"Parse error: {e}")
#         return []
# 
# 
# def load_test_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 item = json.loads(line)
#                 data.append({
#                     '_id': item.get('_id', ''),
#                     'text': item.get('text', ''),
#                     'conspiracy': item.get('conspiracy', 'No')
#                 })
#             except json.JSONDecodeError:
#                 continue
#     return data
# 
# 
# def predict_batch(model, tokenizer, texts):
#     prompts = [format_prompt(text) for text in texts]
# 
#     inputs = tokenizer(
#         prompts,
#         return_tensors="pt",
#         padding=True,
#         truncation=True,
#         max_length=512
#     ).to(model.device)
# 
#     with torch.no_grad():
#         outputs = model.generate(
#             **inputs,
#             max_new_tokens=MAX_NEW_TOKENS,
#             temperature=0.3,
#             do_sample=True,
#             top_p=0.9,
#             pad_token_id=tokenizer.eos_token_id
#         )
# 
#     predictions = []
#     for i, output in enumerate(outputs):
#         input_length = inputs['input_ids'][i].shape[0]
#         generated_tokens = output[input_length:]
#         generated_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
#         markers = extract_markers_from_generation(generated_text, texts[i])
#         predictions.append(markers)
# 
#     return predictions
# 
# 
# def main():
#     print("Loading model and tokenizer...")
#     model, tokenizer = load_model_and_tokenizer()
# 
#     print(f"Loading test data from {TEST_FILE}")
#     test_data = load_test_data(TEST_FILE)
#     print(f"Loaded {len(test_data)} samples")
# 
#     results = []
# 
#     print("Running inference...")
#     for i in tqdm(range(0, len(test_data), BATCH_SIZE)):
#         batch = test_data[i:i + BATCH_SIZE]
#         texts = [item['text'] for item in batch]
#         ids = [item['_id'] for item in batch]
#         conspiracy_labels = [item['conspiracy'] for item in batch]
# 
#         predictions = predict_batch(model, tokenizer, texts)
# 
#         for doc_id, conspiracy, markers in zip(ids, conspiracy_labels, predictions):
#             results.append({
#                 '_id': doc_id,
#                 'conspiracy': conspiracy,
#                 'markers': markers
#             })
# 
#     print(f"Saving predictions to {SUBMISSION_FILE}")
#     with open(SUBMISSION_FILE, 'w') as f:
#         for result in results:
#             f.write(json.dumps(result) + '\n')
# 
#     total_markers = sum(len(r['markers']) for r in results)
#     samples_with_markers = sum(1 for r in results if r['markers'])
#     avg_markers = total_markers / len(results) if results else 0
# 
#     print(f"\nInference completed!")
#     print(f"Total predictions: {len(results)}")
#     print(f"Samples with markers: {samples_with_markers}")
#     print(f"Total markers extracted: {total_markers}")
#     print(f"Average markers per sample: {avg_markers:.2f}")
# 
# 
# if __name__ == "__main__":
#     main()

!python infer_llama_span.py

