# -*- coding: utf-8 -*-
"""robert_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vSlqfrecmz5AyV-KgCpyam-tMiiNjWg
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_model_generic.py
# import json
# import argparse
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForSequenceClassification,
#     TrainingArguments,
#     Trainer,
#     DataCollatorWithPadding
# )
# from sklearn.model_selection import train_test_split
# import numpy as np
# from sklearn.metrics import f1_score, accuracy_score
# import torch
# 
# def compute_metrics(eval_pred):
#     """Compute metrics during evaluation"""
#     predictions, labels = eval_pred
#     predictions = np.argmax(predictions, axis=1)
#     return {
#         'accuracy': accuracy_score(labels, predictions),
#         'f1': f1_score(labels, predictions, average='weighted')
#     }
# 
# def load_and_filter_data(file_path):
#     """Load training data and filter out 'Can't tell' labels"""
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             item = json.loads(line)
#             if item.get('conspiracy') in ['Yes', 'No']:
#                 data.append(item)
#     return data
# 
# def main(model_name, output_dir, batch_size=8, learning_rate=2e-5, epochs=5):
#     print(f"\n🔹 Training model: {model_name}")
# 
#     # GPU check
#     if torch.cuda.is_available():
#         print(f"✅ Using GPU: {torch.cuda.get_device_name(0)}")
#     else:
#         print("⚠️ GPU not available, training on CPU.")
# 
#     # Load data
#     train_file = "train_rehydrated.jsonl"
#     data = load_and_filter_data(train_file)
#     print(f"Loaded {len(data)} labeled samples")
# 
#     # Split into train/validation
#     train_data, val_data = train_test_split(
#         data,
#         test_size=0.1,
#         random_state=42,
#         stratify=[d['conspiracy'] for d in data]
#     )
# 
#     print(f"Train: {len(train_data)}, Validation: {len(val_data)}")
# 
#     # Convert to HuggingFace Dataset
#     train_dataset = Dataset.from_list(train_data)
#     val_dataset = Dataset.from_list(val_data)
# 
#     # Label mapping
#     label2id = {"No": 0, "Yes": 1}
#     id2label = {0: "No", 1: "Yes"}
# 
#     # Add numeric labels
#     def add_labels(example):
#         example['labels'] = label2id[example['conspiracy']]
#         return example
# 
#     train_dataset = train_dataset.map(add_labels)
#     val_dataset = val_dataset.map(add_labels)
# 
#     # Load tokenizer
#     print(f"Loading tokenizer and model: {model_name}")
# 
#     if "bertweet" in model_name.lower():
#         print("🔸 Using BERTweet tokenizer with normalization")
#         tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False, normalization=True)
#         max_len = 128
#     elif "deberta" in model_name.lower():
#         print("🔸 Using DeBERTa tokenizer (longer sequences, gradient checkpointing ON)")
#         tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
#         max_len = 256
#     else:
#         tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
#         max_len = 128
# 
#     model = AutoModelForSequenceClassification.from_pretrained(
#         model_name,
#         num_labels=2,
#         id2label=id2label,
#         label2id=label2id
#     )
# 
#    # if "deberta" in model_name.lower():
#     #    model.gradient_checkpointing_enable()
# 
#     # Tokenize datasets
#     def tokenize_function(examples):
#         if tokenizer.pad_token is None:
#             tokenizer.pad_token = tokenizer.eos_token
#         return tokenizer(
#             examples["text"],
#             truncation=True,
#             max_length=max_len,
#             padding=False
#         )
# 
#     print("Tokenizing datasets...")
#     train_dataset = train_dataset.map(tokenize_function, batched=True)
#     val_dataset = val_dataset.map(tokenize_function, batched=True)
# 
#     data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
# 
#     # ✅ TrainingArguments
#     training_args = TrainingArguments(
#         output_dir=output_dir,
#         eval_strategy="epoch",    # <-- works with latest transformers
#         save_strategy="epoch",
#         learning_rate=learning_rate,
#         per_device_train_batch_size=batch_size,
#         per_device_eval_batch_size=batch_size,
#         num_train_epochs=epochs,
#         weight_decay=0.01,
#         save_total_limit=2,
#         load_best_model_at_end=True,
#         metric_for_best_model="f1",
#         fp16=torch.cuda.is_available(),
#         push_to_hub=False,
#         report_to="none",
#         logging_steps=100,
#         dataloader_num_workers=0,
#     )
# 
#     trainer = Trainer(
#         model=model,
#         args=training_args,
#         train_dataset=train_dataset,
#         eval_dataset=val_dataset,
#         tokenizer=tokenizer,
#         data_collator=data_collator,
#         compute_metrics=compute_metrics
#     )
# 
#     print("\n🚀 Starting training...")
#     trainer.train()
# 
#     # Save model
#     trainer.save_model(output_dir)
#     tokenizer.save_pretrained(output_dir)
#     print(f"\n✅ Model saved to {output_dir}")
# 
#     print("\n📊 Final evaluation on validation set:")
#     results = trainer.evaluate()
#     print(results)
# 
# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument("--model_name", type=str, required=True)
#     parser.add_argument("--output_dir", type=str, required=True)
#     parser.add_argument("--batch_size", type=int, default=8)
#     parser.add_argument("--learning_rate", type=float, default=2e-5)
#     parser.add_argument("--epochs", type=int, default=5)
#     args = parser.parse_args()
#     main(
#         model_name=args.model_name,
#         output_dir=args.output_dir,
#         batch_size=args.batch_size,
#         learning_rate=args.learning_rate,
#         epochs=args.epochs
#     )
#

!python train_model_generic.py \
    --model_name roberta-large \
    --output_dir roberta-large-conspiracy-v2 \
    --batch_size 16 \
    --learning_rate 1e-5 \
    --epochs 5

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer_roberta.py
# import json
# import sys
# import numpy as np
# import os
# import glob
# from datasets import Dataset
# from transformers import (
#     AutoTokenizer,
#     AutoModelForSequenceClassification,
#     Trainer,
#     DataCollatorWithPadding,
#     TrainingArguments,
# )
# import torch
# import torch.nn.functional as F
# 
# MODEL_PATH = "roberta-large-conspiracy-v2"  # Note: v2!
# TEST_FILE = "dev_rehydrated.jsonl"
# SUBMISSION_FILE = "submission_roberta.jsonl"
# MODEL_NAME = "roberta-large"
# LABEL_MAP = {0: "No", 1: "Yes"}
# BATCH_SIZE = 64
# 
# def find_latest_checkpoint(base_path):
#     checkpoint_dirs = glob.glob(os.path.join(base_path, "checkpoint-*"))
#     if not checkpoint_dirs:
#         print(f"No checkpoint found. Using: {base_path}")
#         return base_path
#     checkpoint_dirs.sort(key=lambda x: int(os.path.basename(x).split('-')[-1]))
#     latest_checkpoint = checkpoint_dirs[-1]
#     print(f"Found latest checkpoint: {latest_checkpoint}")
#     return latest_checkpoint
# 
# def load_competition_test_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for i, line in enumerate(f):
#             try:
#                 item = json.loads(line)
#                 sample_id = item.get("_id", f"sample_{i}")
#                 data.append({
#                     "unique_sample_id": sample_id,
#                     "text": item.get("text", "")
#                 })
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line at index {i}")
#     print(f"Loaded {len(data)} samples for inference.")
#     return data
# 
# def tokenize_data(dataset, tokenizer):
#     return dataset.map(
#         lambda examples: tokenizer(
#             examples["text"],
#             truncation=True,
#             max_length=512
#         ),
#         batched=True
#     )
# 
# if __name__ == '__main__':
#     raw_data = load_competition_test_data(TEST_FILE)
#     if not raw_data:
#         print("Error: No data loaded.")
#         sys.exit(-1)
# 
#     test_dataset = Dataset.from_list(raw_data)
#     unique_ids = test_dataset["unique_sample_id"]
# 
#     model_directory = find_latest_checkpoint(MODEL_PATH)
#     print(f"Loading model from {model_directory}...")
# 
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
#     model = AutoModelForSequenceClassification.from_pretrained(model_directory)
# 
#     tokenized_test_dataset = tokenize_data(test_dataset, tokenizer)
#     tokenized_test_dataset = tokenized_test_dataset.remove_columns(["unique_sample_id", "text"])
# 
#     data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
#     prediction_args = Trainer(
#         model=model,
#         args=TrainingArguments(
#             output_dir="./tmp_inference_roberta",
#             per_device_eval_batch_size=BATCH_SIZE,
#             report_to="none"
#         ),
#         data_collator=data_collator
#     )
# 
#     print("🚀 Starting prediction...")
#     predictions_output = prediction_args.predict(tokenized_test_dataset)
# 
#     logits = predictions_output.predictions
#     predicted_class_ids = np.argmax(logits, axis=-1)
#     probs = F.softmax(torch.tensor(logits), dim=-1).numpy()
#     predicted_labels = [LABEL_MAP[int(id)] for id in predicted_class_ids]
# 
#     print(f"Saving predictions to {SUBMISSION_FILE}...")
#     jsonl_lines = []
#     for i, label in enumerate(predicted_labels):
#         jsonl_obj = {
#             "_id": unique_ids[i],
#             "conspiracy": label,
#             "prob_no": float(probs[i][0]),
#             "prob_yes": float(probs[i][1])
#         }
#         jsonl_lines.append(json.dumps(jsonl_obj))
# 
#     with open(SUBMISSION_FILE, 'w') as f:
#         f.write('\n'.join(jsonl_lines) + '\n')
# 
#     print(f"✅ Submission file '{SUBMISSION_FILE}' generated!")
#     print("\n📊 Sample predictions:")
#     for i in range(min(3, len(jsonl_lines))):
#         print(json.dumps(json.loads(jsonl_lines[i]), indent=2))

!python infer_roberta.py