# -*- coding: utf-8 -*-
"""NLP_TASK2_robertav3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NlYSCTR4vWm4UWfNludYuPrilKtqPuc
"""

from google.colab import drive
drive.mount('/content/drive')



!pip install -r requirements.txt

!pip install transformers==4.44.2 peft==0.11.1 accelerate==0.33.0 datasets==3.0.1 sentencepiece

import transformers, peft, accelerate
print("Transformers:", transformers.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

 
# %%writefile train_one_span_roberta.py
# import json
# from transformers import RobertaTokenizerFast, RobertaForTokenClassification
# from transformers import TrainingArguments, Trainer, DataCollatorForTokenClassification
# from datasets import Dataset
# import torch
# 
# 
# def load_data(file_path):
#     data = []
#     with open(file_path, 'r') as f:
#         for line in f:
#             try:
#                 data.append(json.loads(line))
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line: {line.strip()}")
#     return data
# 
# 
# def create_label_maps_simplified(marker_type):
#     label_list = ["O", marker_type]
#     label_to_id = {label: i for i, label in enumerate(label_list)}
#     id_to_label = {i: label for label, i in label_to_id.items()}
#     return label_to_id, id_to_label, len(label_list)
# 
# 
# def tokenize_and_align_labels_simplified(examples, tokenizer, label_to_id, marker_type):
#     tokenized_inputs = tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128,
#                                  return_offsets_mapping=True)
#     labels = []
#     all_markers = examples.get("markers", [])
# 
#     for i, offsets in enumerate(tokenized_inputs["offset_mapping"]):
#         example_labels = [0] * len(offsets)  # Initialize with 'O'
#         example_markers = all_markers[i] if i < len(all_markers) else []
# 
#         for marker in example_markers:
#             if marker["type"] == marker_type:
#                 start_char = marker["startIndex"]
#                 end_char = marker["endIndex"]
#                 marker_label = label_to_id.get(marker_type)
#                 if marker_label is not None:
#                     for token_idx, (start, end) in enumerate(offsets):
#                         if start is not None and end is not None:
#                             if start_char <= start < end_char:
#                                 if token_idx < len(example_labels):
#                                     example_labels[token_idx] = marker_label
#                             elif start < end_char and end > start_char:  # Handle partial overlaps
#                                 if token_idx < len(example_labels) and example_labels[token_idx] == 0:
#                                     example_labels[token_idx] = marker_label
#         labels.append(example_labels)
#     tokenized_inputs["labels"] = labels
#     return tokenized_inputs
# 
# 
# if __name__ == "__main__":
#     train_file = "train_rehydrated.jsonl"
#     model_name = "roberta-large"  # Changed from distilbert-base-uncased
#     output_dir_base = "roberta-large-single-type-simplified"  # Changed output directory name
# 
#     # Adjusted hyperparameters for RoBERTa-large
#     batch_size = 8  # Reduced from 16 due to larger model
#     learning_rate = 1e-5  # Reduced from 2e-5 for stability
#     num_epochs = 5  # Reduced from 10 (large models train faster)
# 
#     marker_types_to_train = ["Action", "Actor", "Effect", "Evidence", "Victim"]
#     all_results = {}
# 
#     # Check GPU availability
#     device = "cuda" if torch.cuda.is_available() else "cpu"
#     print(f"Using device: {device}")
# 
#     # Load data once
#     print("Loading training data...")
#     train_data = load_data(train_file)
#     print(f"Loaded {len(train_data)} training samples")
#     train_dataset = Dataset.from_list(train_data)
# 
#     print(f"Loading tokenizer: {model_name}")
#     tokenizer = RobertaTokenizerFast.from_pretrained(model_name)  # Changed tokenizer
# 
#     for marker_type in marker_types_to_train:
#         print(f"\n{'='*60}")
#         print(f"Training model for marker type: {marker_type}")
#         print(f"{'='*60}")
# 
#         # Create simplified label maps
#         label_to_id, id_to_label, num_labels = create_label_maps_simplified(marker_type)
#         print("Label to ID mapping:", label_to_id)
#         print("ID to Label mapping:", id_to_label)
#         print("Number of labels:", num_labels)
# 
#         # Tokenize and align labels (simplified)
#         print("Tokenizing and aligning labels...")
#         tokenized_train_dataset = train_dataset.map(
#             tokenize_and_align_labels_simplified,
#             batched=True,
#             fn_kwargs={"tokenizer": tokenizer, "label_to_id": label_to_id, "marker_type": marker_type}
#         )
# 
#         # Load a new model for each marker type
#         print(f"Loading model: {model_name}")
#         model = RobertaForTokenClassification.from_pretrained(model_name, num_labels=num_labels)  # Changed model
# 
#         # Define training arguments
#         output_dir = f"{output_dir_base}-{marker_type}"
#         training_args = TrainingArguments(
#             output_dir=output_dir,
#             learning_rate=learning_rate,
#             per_device_train_batch_size=batch_size,
#             num_train_epochs=num_epochs,
#             weight_decay=0.01,
#             logging_dir=f'./logs-{marker_type}-roberta',
#             logging_steps=50,
#             save_strategy="epoch",
#             report_to="none",
#             fp16=torch.cuda.is_available(),  # Enable mixed precision if GPU available
#         )
# 
#         data_collator = DataCollatorForTokenClassification(tokenizer)
# 
#         trainer = Trainer(
#             model=model,
#             args=training_args,
#             train_dataset=tokenized_train_dataset,
#             data_collator=data_collator,
#             tokenizer=tokenizer,
#         )
# 
#         # Train
#         print(f"Starting training for {marker_type}...")
#         trainer.train()
#         print(f" Training for {marker_type} finished!")
#         print(f"Model saved to: {output_dir}")
# 
#     print(f"\n{'='*60}")
#     print("All models trained successfully!")
#     print(f"{'='*60}")

!python train_one_span_roberta.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile infer_one_span_roberta.py
# import json
# import sys
# import numpy as np
# import os
# import glob
# from datasets import Dataset
# from transformers import (
#     RobertaTokenizerFast,
#     RobertaForTokenClassification,
#     Trainer,
#     DataCollatorForTokenClassification,
#     TrainingArguments,
# )
# from collections import defaultdict
# 
# MODEL_PATH_BASE = "roberta-large-single-type-simplified"
# MARKER_TYPES_TO_INFER = ["Action", "Actor", "Effect", "Evidence", "Victim"]
# TEST_FILE = "dev_rehydrated.jsonl"
# SUBMISSION_FILE = "submission.jsonl"
# MODEL_NAME = "roberta-large"
# BATCH_SIZE = 8
# 
# 
# def find_latest_checkpoint(base_path, marker_type):
#     """
#     Scans the type-specific base_path directory for the latest numbered 'checkpoint-*' subfolder.
#     """
#     full_path = f"{base_path}-{marker_type}"
#     checkpoint_dirs = glob.glob(os.path.join(full_path, "checkpoint-*"))
# 
#     if not checkpoint_dirs:
#         print(f"Warning: No 'checkpoint-*' folder found. Assuming model files are in: {full_path}")
#         return full_path
# 
#     checkpoint_dirs.sort(key=lambda x: int(os.path.basename(x).split('-')[-1]))
# 
#     latest_checkpoint = checkpoint_dirs[-1]
#     print(f"Found latest checkpoint: {latest_checkpoint}")
#     return latest_checkpoint
# 
# 
# def load_data(file_path):
#     """Loads all data from a JSONL file, preserving order, and retaining the unique ID."""
#     data = []
#     with open(file_path, 'r') as f:
#         for i, line in enumerate(f):
#             try:
#                 item = json.loads(line.strip())
#                 item["_id"] = item.get("_id", f"sample_{i}")
#                 item["text"] = item.get("text", "")
#                 item["markers"] = item.get("markers", [])
# 
#                 # CRITICAL FIX: Handle null conspiracy values
#                 conspiracy_value = item.get("conspiracy")
#                 if conspiracy_value is None or conspiracy_value not in ["Yes", "No"]:
#                     item["conspiracy"] = "No"  # Default to "No" if null or invalid
#                 else:
#                     item["conspiracy"] = conspiracy_value
# 
#                 data.append(item)
#             except json.JSONDecodeError:
#                 print(f"Skipping invalid JSON line at index {i} in {file_path}: {line.strip()}")
#     print(f"Loaded {len(data)} samples for inference.")
#     return data
# 
# 
# def tokenize_and_align_labels(examples, tokenizer, label_to_id):
#     """Tokenizes the text and returns inputs with offset mapping for post-processing."""
#     tokenized_inputs = tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128,
#                                  return_offsets_mapping=True)
#     tokenized_inputs["labels"] = [[-100] * len(offset_map) for offset_map in tokenized_inputs["offset_mapping"]]
#     return tokenized_inputs
# 
# 
# def reconstruct_spans(predictions, tokenized_dataset, id_to_label):
#     """
#     Converts token-level predictions (O vs TYPE) back into a list of character spans.
#     """
#     reconstructed_markers = defaultdict(list)
#     positive_label_type = id_to_label.get(1)
# 
#     if not positive_label_type or positive_label_type == "O":
#         print("Error: Model configuration does not match simplified binary training.")
#         return reconstructed_markers
# 
#     for i, pred_ids in enumerate(predictions):
#         offsets = tokenized_dataset[i]['offset_mapping']
#         original_text = tokenized_dataset[i]['text']
#         current_span_start_char = None
# 
#         for token_idx, label_id in enumerate(pred_ids):
#             offset_tuple = offsets[token_idx]
#             is_special = (offset_tuple is None or offset_tuple[0] is None or offset_tuple[1] is None or
#                          (offset_tuple[0] == 0 and offset_tuple[1] == 0))
# 
#             if is_special:
#                 if current_span_start_char is not None:
#                     prev_end_char = None
#                     if token_idx > 0 and offsets[token_idx - 1][1] is not None:
#                         prev_end_char = offsets[token_idx - 1][1]
#                     if prev_end_char is not None:
#                         span_text = original_text[current_span_start_char:prev_end_char]
#                         reconstructed_markers[i].append({
#                             "startIndex": current_span_start_char,
#                             "endIndex": prev_end_char,
#                             "type": positive_label_type,
#                             "text": span_text
#                         })
#                     current_span_start_char = None
#                 continue
# 
#             label = id_to_label[label_id]
#             start_char = offset_tuple[0]
# 
#             if label == positive_label_type:
#                 if current_span_start_char is None:
#                     current_span_start_char = start_char
#             elif label == 'O':
#                 if current_span_start_char is not None:
#                     prev_end_char = offsets[token_idx - 1][1] if token_idx > 0 and offsets[token_idx - 1][1] is not None else start_char
#                     span_text = original_text[current_span_start_char:prev_end_char]
#                     reconstructed_markers[i].append({
#                         "startIndex": current_span_start_char,
#                         "endIndex": prev_end_char,
#                         "type": positive_label_type,
#                         "text": span_text
#                     })
#                     current_span_start_char = None
# 
#         if current_span_start_char is not None:
#             last_valid_end = None
#             last_token_idx = len(pred_ids) - 1
#             while last_token_idx >= 0:
#                 offset_tuple_end = offsets[last_token_idx]
#                 if offset_tuple_end is not None and offset_tuple_end[1] is not None and offset_tuple_end[1] != 0:
#                     last_valid_end = offset_tuple_end[1]
#                     break
#                 last_token_idx -= 1
#             if last_valid_end is not None:
#                 span_text = original_text[current_span_start_char:last_valid_end]
#                 reconstructed_markers[i].append({
#                     "startIndex": current_span_start_char,
#                     "endIndex": last_valid_end,
#                     "type": positive_label_type,
#                     "text": span_text
#                 })
# 
#     return reconstructed_markers
# 
# 
# if __name__ == '__main__':
#     # 1. Load Data
#     raw_data = load_data(TEST_FILE)
#     if not raw_data:
#         print("Error: No data loaded. Cannot perform inference.")
#         sys.exit(-1)
# 
#     unique_ids = [d["_id"] for d in raw_data]
#     conspiracy_keys = [d["conspiracy"] for d in raw_data]
# 
#     # Verify conspiracy values are valid
#     print(f"\n=== Conspiracy Value Check ===")
#     null_count = sum(1 for c in conspiracy_keys if c is None)
#     yes_count = sum(1 for c in conspiracy_keys if c == "Yes")
#     no_count = sum(1 for c in conspiracy_keys if c == "No")
#     print(f"Yes: {yes_count}, No: {no_count}, Null: {null_count}")
# 
#     if null_count > 0:
#         print(f"WARNING: Found {null_count} null conspiracy values - they will be set to 'No'")
# 
#     test_dataset = Dataset.from_list(raw_data)
#     tokenizer = RobertaTokenizerFast.from_pretrained(MODEL_NAME)
#     dummy_label_to_id = {"O": 0}
# 
#     tokenized_test_dataset = test_dataset.map(
#         tokenize_and_align_labels,
#         batched=True,
#         remove_columns=[col for col in test_dataset.column_names if
#                         col not in ['text', 'offset_mapping', '_id', 'conspiracy']],
#         fn_kwargs={"tokenizer": tokenizer, "label_to_id": dummy_label_to_id}
#     )
# 
#     all_predicted_markers = defaultdict(list)
# 
#     # 2. Iterate and Infer for Each Marker Type
#     for marker_type in MARKER_TYPES_TO_INFER:
#         model_directory = find_latest_checkpoint(MODEL_PATH_BASE, marker_type)
#         print(f"\n{'='*60}")
#         print(f"Running inference for type: {marker_type}")
#         print(f"{'='*60}")
#         print(f"Loading model from: {model_directory}")
# 
#         try:
#             model = RobertaForTokenClassification.from_pretrained(model_directory)
#             id_to_label = {0: "O", 1: marker_type}
#             print(f"Using defined labels for reconstruction: {id_to_label}")
#         except Exception as e:
#             print(f"Error loading model for {marker_type} from '{model_directory}'. Details: {e}")
#             continue
# 
#         data_collator = DataCollatorForTokenClassification(tokenizer)
#         prediction_args = Trainer(
#             model=model,
#             args=TrainingArguments(
#                 output_dir=f"./tmp_inference_span_{marker_type}",
#                 per_device_eval_batch_size=BATCH_SIZE,
#                 report_to="none"
#             ),
#             data_collator=data_collator,
#             tokenizer=tokenizer
#         )
# 
#         print(f"Starting prediction for {marker_type}...")
#         predictions_output = prediction_args.predict(tokenized_test_dataset)
#         logits = predictions_output.predictions
#         predicted_class_ids = np.argmax(logits, axis=2)
# 
#         print(f"Reconstructing character spans for {marker_type}...")
#         current_marker_map = reconstruct_spans(predicted_class_ids, tokenized_test_dataset, id_to_label)
# 
#         for i, markers in current_marker_map.items():
#             all_predicted_markers[i].extend(markers)
# 
#         print(f"✓ Completed inference for {marker_type}")
# 
#     print(f"\n{'='*60}")
#     print(f"Saving final predictions to {SUBMISSION_FILE}")
#     print(f"{'='*60}")
# 
#     jsonl_lines = []
#     for i in range(len(raw_data)):
#         predicted_markers = all_predicted_markers.get(i, [])
# 
#         # CRITICAL: Ensure conspiracy is a valid string
#         conspiracy_val = conspiracy_keys[i]
#         if conspiracy_val is None or conspiracy_val not in ["Yes", "No"]:
#             conspiracy_val = "No"
# 
#         jsonl_obj = {
#             "_id": unique_ids[i],
#             "conspiracy": conspiracy_val,
#             "markers": predicted_markers
#         }
# 
#         # Format with proper spacing to match friend's format
#         jsonl_lines.append(json.dumps(jsonl_obj, separators=(', ', ': '), ensure_ascii=False))
# 
#     with open(SUBMISSION_FILE, 'w', encoding='utf-8') as f:
#         f.write('\n'.join(jsonl_lines) + '\n')
# 
#     print(f" Submission file '{SUBMISSION_FILE}' generated successfully!")
# 
# 
#

!python infer_one_span_roberta.py

!zip submission.zip submission.jsonl

